<?php

namespace Sbehnfeldt\Webapp;

use Slim\App;
use Psr\Http\Message\ResponseInterface as Response;
use Psr\Http\Message\ServerRequestInterface as Request;


class WebApp extends App
{

    public function run($silent = false)
    {
        $this->get('/', function (Request $req, Response $resp, array $args) {
            $resp->getBody()->write( '123');
            return $resp;
        });
        return parent::run($silent); // TODO: Change the autogenerated stub
    }
}
