<?php

namespace Sbehnfeldt\Webapp;

use Slim\App;
use Psr\Http\Message\ResponseInterface as Response;
use Psr\Http\Message\ServerRequestInterface as Request;


class WebApp extends App
{
    private $renderer;

    public function __construct($container = [])
    {
        parent::__construct($container);
        $this->renderer = null;
    }


    /**
     * @return mixed
     */
    public function getRenderer()
    {
        if (!$this->renderer) {
            if ($this->getContainer()->has('renderer')) {
                $this->renderer = $this->getContainer()->get('renderer');
            }
            if (!$this->renderer) {
                $this->renderer = new TwigPageRenderer($this->getContainer()->get('settings')->get('twig'));
            }
        }
        return $this->renderer;
    }

    /**
     * @param mixed $renderer
     */
    public function setRenderer($renderer): void
    {
        $this->renderer = $renderer;
    }


    public function login(string $username, string $password): bool
    {
        if (!$username) {
            return false;
        }
        if (!$password) {
            return false;
        }
        return true;
    }



    public function run($silent = false)
    {
        $web = $this;

        $this->get('/', function (Request $req, Response $resp, array $args) use ($web) {
            $resp->getBody()->write($web->getRenderer()->render(IPageRenderer::PAGE_INDEX, []));
            return $resp;
        });

        $this->get('/login', function (Request $req, Response $resp, array $args) use ($web) {
            $resp->getBody()->write($web->getRenderer()->render(IPageRenderer::PAGE_LOGIN, []));
            return $resp;
        });

        $this->post('/login', function (Request $req, Response $resp, array $args) use ($web) {
            try {
                if (!$web->login($_POST['username'], $_POST['password'])) {
                    throw new \Exception('Unauthorized');
                }
                $resp = $resp->withHeader( 'Location', '/');
            } catch (\Exception $e) {
                $resp->getBody()->write($web->getRenderer()->render(IPageRenderer::PAGE_LOGIN, []));
            }
            return $resp;
        });


        return parent::run($silent); // TODO: Change the autogenerated stub
    }
}
